### ISSUE TITLE
/bin/bash: expect: command not found

### ISSUE THREAD

**Issue by icanalmostseeyou** [hesselbom/vim-hsftp#10]
After vim-hsftp installed
I tried to run :Hupload

And there's error
`/bin/bash: expect: command not found`

OS Ubuntu 16, vim 7.4

How to fix this?
Thankyou

**Comment by icanalmostseeyou** [comment]
Working after install expect.

`sudo apt install expect`

**Comment by zhangliyuan97** [comment]
thanks for your help.
