### ISSUE TITLE
upload on save?

### ISSUE THREAD

**Issue by pyaf** [hesselbom/vim-hsftp#14]
Hi, I really appreciate your effort for `vim-hsftp` plugin, I really like it. Does it have any feature of uploading file on save?

**Comment by kolosseo** [comment]
> Hi, I really appreciate your effort for `vim-hsftp` plugin, I really like it. Does it have any feature of uploading file on save?

pyaf, I just published a fork who does exactly this: https://github.com/kolosseo/vim-easy-sync

**Comment by pyaf** [comment]
@kolosseo Thannk you so much!, will check it out soon.

**Comment by hozza** [comment]
@pyaf an auto upload feature should be implemented shortly when pull-request #15 is merged (coming soon!).

**Comment by hozza** [comment]
@kolosseo it looks like your project fork has moved on quite a bit from vim-hsftp in recent years - but if you do have improvements you'd like to contribute feel free to submit them as a pull-request!

**Comment by kolosseo** [comment]
@hozza yes, I moved a bit forward to use rsync also, but my project is actually not complete.

Anyway, to add the auto upload on save, should work by simply adding this line at the end of the script:
```
autocmd BufWritePost * :call H_UploadFile()
```

**Comment by hozza** [comment]
@kolosseo thanks! I've got a PR with a similar solution - too be merged soon!
